import Link from "next/link";
import { AstroCard } from "@/components/ui/AstroCard";
import { PageHeader } from "@/components/ui/PageHeader";
import { PageShell } from "@/components/ui/PageShell";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Editorial Methodology & Corrections",
  description: "How Astroboat uses astronomy sources, automated summaries, AI assistance, image credits, updates, and corrections.",
  path: "/editorial-policy"
});

export default function EditorialPolicyPage() {
  return (
    <PageShell className="max-w-4xl">
      <PageHeader title="Editorial methodology" subtitle="How Astroboat sources information, explains it, and handles corrections." />
      <AstroCard as="article" className="space-y-8 p-6 text-sm leading-7 text-astro-muted sm:p-8">
        <section><h2 className="font-display text-2xl text-astro-text">Sources and live data</h2><p className="mt-3">Astroboat draws astronomy updates from publisher feeds and live data from named agencies and services. Each brief links to its original publisher. Live tool data identifies its provider and, where available, its observation date or update time. See the <Link href="/data-sources" className="text-astro-blue underline">data sources</Link> page for the provider list.</p></section>
        <section><h2 className="font-display text-2xl text-astro-text">Briefs and original guides</h2><p className="mt-3">Most briefs are automatically extracted and shortened from source feeds. Their category and “why it matters” text are rule-based context, not independent reporting or a verification of the source’s claims. These source digests are excluded from search indexing. Editorial guides are written for Astroboat, checked against linked primary sources, and have their own publication date.</p></section>
        <section><h2 className="font-display text-2xl text-astro-text">Automation and AI</h2><p className="mt-3">Feed parsing, brief summaries, tags, and some tool explanations are generated by code. Astroboat’s question assistant uses an AI model and can make mistakes; it is not the source of live Moon, event, or asteroid records. The NEO guide was prepared with AI assistance against the linked NASA/JPL sources. AI-assisted guides identify that process on the page; the site owner should review copy and sources before publication.</p></section>
        <section><h2 className="font-display text-2xl text-astro-text">Dates, corrections, and images</h2><p className="mt-3">Published dates refer to the original source or guide. Updated dates appear only when editorial content changes. “Last checked” means a data request was made, not that every upstream fact has changed. Images retain source credits where supplied; the original provider remains the authority for reuse rights. To report an error, broken source, or missing credit, use the <Link href="/contact" className="text-astro-blue underline">contact page</Link>. Corrections to guides should update their recorded date.</p></section>
      </AstroCard>
    </PageShell>
  );
}
