import type {
  Article,
  AstronomyBrief,
  LearningPath,
  MoonData,
  NearEarthObject,
  SatellitePass,
  SatelliteStatus,
  SourceInfo,
  SpaceEvent,
  ToolCard
} from "@/lib/types";

export const sources: SourceInfo[] = [
  { id: "nasa", name: "NASA", kind: "agency", credibility: "Primary" },
  { id: "esa", name: "ESA", kind: "agency", credibility: "Primary" },
  { id: "jpl", name: "JPL", kind: "archive", credibility: "Primary" },
  { id: "usno", name: "USNO", kind: "archive", credibility: "Primary" },
  { id: "space-devs", name: "Space Devs", kind: "platform", credibility: "Reviewed" },
  { id: "arxiv", name: "arXiv", kind: "research", credibility: "Preprint" },
  { id: "isro", name: "ISRO", kind: "agency", credibility: "Primary" },
  { id: "astroboat", name: "Astroboat", kind: "internal", credibility: "Editorial" }
];

const sourceById = (id: SourceInfo["id"]) => {
  const source = sources.find((item) => item.id === id);

  if (!source) {
    throw new Error(`Missing mock source: ${id}`);
  }

  return source;
};

export const briefs: AstronomyBrief[] = [
  {
    id: "brief-001",
    slug: "webb-temperate-exoplanet-atmosphere",
    source: sourceById("nasa"),
    originalUrl: "#",
    title: "Webb observations refine atmospheric clues around a temperate exoplanet",
    summary: [
      "A new observing pass compared starlight before and during transit.",
      "The signal hints at a thin atmosphere but still needs follow-up.",
      "Clouds and stellar activity remain possible explanations.",
      "The result is strongest when combined with previous Webb spectra.",
      "Researchers are planning more visits to reduce uncertainty."
    ],
    why: "It shows how cautious exoplanet science can still move quickly when multiple observations are combined.",
    tags: ["Exoplanets", "Webb", "Spectroscopy"],
    readingTime: "4 min",
    publishedAt: "2026-05-11"
  },
  {
    id: "brief-002",
    slug: "solar-orbiter-fast-cme",
    source: sourceById("esa"),
    originalUrl: "#",
    title: "Solar Orbiter tracks a fast coronal mass ejection across the inner heliosphere",
    summary: [
      "The spacecraft observed the eruption while closer to the Sun than Earth.",
      "Its instruments measured both imaging and in-situ plasma data.",
      "The event gave forecasters a cleaner view of particle arrival timing.",
      "Earth was not in the main path of the disturbance.",
      "The dataset helps improve space-weather models."
    ],
    why: "Better CME timing helps protect satellites, astronauts, and power infrastructure without alarmist reporting.",
    tags: ["Sun", "Space Weather", "ESA"],
    readingTime: "5 min",
    publishedAt: "2026-05-10"
  },
  {
    id: "brief-003",
    slug: "small-main-belt-asteroid-rotation",
    source: sourceById("arxiv"),
    originalUrl: "#",
    title: "A survey of small main-belt asteroids finds new rotation patterns",
    summary: [
      "The study compared light curves from several survey telescopes.",
      "Small bodies showed a wider range of spin states than expected.",
      "Some fast rotators may have unusual internal structures.",
      "The sample is still biased toward brighter objects.",
      "Future sky surveys should fill in the missing population."
    ],
    why: "Rotation tells scientists whether small asteroids are solid rock, rubble piles, or something in between.",
    tags: ["Asteroids", "Surveys", "Research"],
    readingTime: "6 min",
    publishedAt: "2026-05-09"
  },
  {
    id: "brief-004",
    slug: "juno-jupiter-polar-cyclones",
    source: sourceById("jpl"),
    originalUrl: "#",
    title: "Juno imagery shows slow changes in Jupiter's polar cyclone pattern",
    summary: [
      "Repeated flybys are revealing how polar storms shift over time.",
      "The cyclones remain stable but show subtle changes in spacing.",
      "Microwave measurements help connect cloud-top views to deeper layers.",
      "The team is comparing the pattern with fluid models.",
      "The long mission timeline is the key scientific advantage."
    ],
    why: "Long-duration spacecraft data helps scientists separate temporary weather from persistent planetary structure.",
    tags: ["Jupiter", "Juno", "Planetary Science"],
    readingTime: "5 min",
    publishedAt: "2026-05-08"
  },
  {
    id: "brief-005",
    slug: "radio-array-maps-milky-way-gas",
    source: sourceById("arxiv"),
    originalUrl: "#",
    title: "Radio survey maps cold hydrogen clouds along the Milky Way's spiral arms",
    summary: [
      "A wide-field radio survey traced neutral hydrogen across the galactic plane.",
      "The map reveals filaments aligned with known spiral-arm structure.",
      "Several regions overlap with active star-forming clouds.",
      "Distance estimates still depend on velocity models.",
      "The catalog will help compare gas structure with infrared dust maps."
    ],
    why: "Hydrogen maps are a practical backbone for understanding where stars can form in our galaxy.",
    tags: ["Milky Way", "Radio Astronomy", "Star Formation"],
    readingTime: "7 min",
    publishedAt: "2026-05-07"
  }
];

export const spaceEvents: SpaceEvent[] = [
  {
    id: "evt-001",
    externalId: "mock-eta-aquariid-peak-2026",
    slug: "eta-aquariid-peak-2026",
    title: "Eta Aquariid meteor shower peak",
    description: "The Eta Aquariids peak as Earth crosses dust left behind by Halley's comet.",
    category: "sky_event",
    status: "scheduled",
    dateUtc: "2026-05-13T04:30:00Z",
    dateDisplay: "May 13, 2026, 04:30 UTC",
    location: "Best from Southern Hemisphere",
    visibility: "Worldwide",
    source: "Mock",
    importance: "medium",
    whyItMatters: "Fast meteors from Halley's comet can leave persistent trains in dark skies."
  },
  {
    id: "evt-002",
    externalId: "mock-commercial-lunar-lander-window",
    slug: "commercial-lunar-lander-window",
    title: "Commercial lunar lander launch window opens",
    description: "A commercial lunar lander launch window opens with small science payloads planned for surface operations.",
    category: "launch",
    status: "scheduled",
    dateUtc: "2026-05-16T22:15:00Z",
    dateDisplay: "May 16, 2026, 22:15 UTC",
    location: "Cape Canaveral, USA",
    visibility: "Online",
    provider: "Commercial provider",
    mission: "Lunar surface payload delivery",
    source: "Mock",
    importance: "high",
    whyItMatters: "The mission carries small science payloads designed for surface operations near lunar sunrise."
  },
  {
    id: "evt-003",
    externalId: "mock-moon-near-spica",
    slug: "moon-near-spica",
    title: "Moon near Spica",
    description: "The Moon passes near Spica in the evening sky, giving observers an easy way to identify Virgo's brightest star.",
    category: "sky_event",
    status: "scheduled",
    dateUtc: "2026-05-20T18:30:00Z",
    dateDisplay: "May 20, 2026, after sunset",
    location: "Global evening skies",
    visibility: "Region-specific",
    source: "Mock",
    importance: "low",
    whyItMatters: "A simple naked-eye pairing that helps beginners identify Virgo's brightest star."
  },
  {
    id: "evt-004",
    externalId: "mock-deep-field-survey-data-release",
    slug: "deep-field-survey-data-release",
    title: "Public release of deep-field galaxy survey data",
    description: "A public archive releases a new deep-field galaxy survey dataset for research teams and independent analysis.",
    category: "space_event",
    status: "scheduled",
    dateUtc: "2026-05-24T15:00:00Z",
    dateDisplay: "May 24, 2026, 15:00 UTC",
    location: "Online archive",
    visibility: "Worldwide",
    source: "Mock",
    importance: "medium",
    whyItMatters: "Fresh survey data often leads to new galaxy evolution studies within days of release."
  },
  {
    id: "evt-005",
    externalId: "mock-venus-evening-elongation",
    slug: "venus-evening-elongation",
    title: "Venus reaches a favorable evening elongation",
    description: "Venus stands well away from the Sun after sunset, making it easy to identify in the western sky.",
    category: "sky_event",
    status: "scheduled",
    dateUtc: "2026-05-27T14:12:00Z",
    dateDisplay: "May 27, 2026, evening local time",
    location: "Western evening sky",
    visibility: "India",
    source: "Mock",
    importance: "low",
    whyItMatters: "Bright planetary apparitions are useful beginner targets and help observers learn sky direction."
  },
  {
    id: "evt-006",
    externalId: "mock-mars-near-praesepe",
    slug: "mars-near-praesepe",
    title: "Mars passes near the Beehive Cluster",
    description: "Mars appears near the Beehive Cluster, creating a useful binocular observing target.",
    category: "sky_event",
    status: "scheduled",
    dateUtc: "2026-06-01T21:00:00Z",
    dateDisplay: "June 1, 2026, evening local time",
    location: "Western evening sky",
    visibility: "Northern Hemisphere",
    source: "Mock",
    importance: "low",
    whyItMatters: "The pairing is a useful binocular target and a good lesson in apparent planetary motion."
  },
  {
    id: "evt-007",
    externalId: "mock-solar-physics-archive-update",
    slug: "solar-physics-archive-update",
    title: "Solar physics archive adds new full-disk magnetogram set",
    description: "A solar archive adds a new full-disk magnetogram set for active-region and space-weather research.",
    category: "space_event",
    status: "scheduled",
    dateUtc: "2026-06-04T12:00:00Z",
    dateDisplay: "June 4, 2026, 12:00 UTC",
    location: "Online archive",
    visibility: "Worldwide",
    source: "Mock",
    importance: "medium",
    whyItMatters: "Magnetograms are core inputs for understanding active regions and space-weather forecasting."
  },
  {
    id: "evt-008",
    externalId: "mock-earth-observation-rideshare-launch",
    slug: "earth-observation-rideshare-launch",
    title: "Earth-observation rideshare mission targeted for launch",
    description: "A rideshare mission is targeted to launch small Earth-observation satellites.",
    category: "launch",
    status: "scheduled",
    dateUtc: "2026-06-09T09:20:00Z",
    dateDisplay: "June 9, 2026, 09:20 UTC",
    location: "Sriharikota, India",
    visibility: "Online",
    provider: "ISRO",
    mission: "Earth observation rideshare",
    source: "Mock",
    importance: "medium",
    whyItMatters: "Small satellites on rideshare missions often expand weather, ocean, and disaster-monitoring coverage."
  }
];

export const moonDashboard: MoonData = {
  date: "2026-05-13",
  locationName: "Ahmedabad, India",
  latitude: 23.0225,
  longitude: 72.5714,
  timezoneOffset: 5.5,
  phaseName: "Waxing Crescent",
  illuminationPercent: 34,
  moonrise: "09:18",
  moonset: "23:04",
  transit: "16:18",
  closestPrimaryPhase: {
    phase: "New Moon",
    dateUtc: "2026-05-16T20:01:00Z",
    dateDisplay: "May 16, 2026, 20:01 UTC",
    timeUtc: "20:01"
  },
  nextFullMoon: {
    phase: "Full Moon",
    dateUtc: "2026-05-31T08:45:00Z",
    dateDisplay: "May 31, 2026, 08:45 UTC",
    timeUtc: "08:45"
  },
  nextNewMoon: {
    phase: "New Moon",
    dateUtc: "2026-05-16T20:01:00Z",
    dateDisplay: "May 16, 2026, 20:01 UTC",
    timeUtc: "20:01"
  },
  upcomingPhases: [
    { phase: "New Moon", dateUtc: "2026-05-16T20:01:00Z", dateDisplay: "May 16, 2026, 20:01 UTC", timeUtc: "20:01" },
    { phase: "First Quarter", dateUtc: "2026-05-23T11:11:00Z", dateDisplay: "May 23, 2026, 11:11 UTC", timeUtc: "11:11" },
    { phase: "Full Moon", dateUtc: "2026-05-31T08:45:00Z", dateDisplay: "May 31, 2026, 08:45 UTC", timeUtc: "08:45" },
    { phase: "Last Quarter", dateUtc: "2026-06-08T10:00:00Z", dateDisplay: "June 8, 2026, 10:00 UTC", timeUtc: "10:00" },
    { phase: "New Moon", dateUtc: "2026-06-15T02:54:00Z", dateDisplay: "June 15, 2026, 02:54 UTC", timeUtc: "02:54" },
    { phase: "First Quarter", dateUtc: "2026-06-21T21:55:00Z", dateDisplay: "June 21, 2026, 21:55 UTC", timeUtc: "21:55" },
    { phase: "Full Moon", dateUtc: "2026-06-29T23:56:00Z", dateDisplay: "June 29, 2026, 23:56 UTC", timeUtc: "23:56" },
    { phase: "Last Quarter", dateUtc: "2026-07-07T19:29:00Z", dateDisplay: "July 7, 2026, 19:29 UTC", timeUtc: "19:29" }
  ],
  photographyScore: 7,
  viewingAdvice: "Crescent phases are useful for casual observing because the terminator creates strong shadow contrast across craters and lunar terrain.",
  beginnerExplanation:
    "A waxing crescent appears after sunset and is useful for learning the terminator, the line where lunar shadows make craters easier to see.",
  source: "Mock",
  isFallback: true
};

export const nearEarthObjects: NearEarthObject[] = [
  {
    id: "2026 KB12",
    externalId: "2026 KB12",
    name: "2026 KB12",
    designation: "2026 KB12",
    closeApproachDate: "2026-05-15",
    closeApproachDateDisplay: "May 15, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-05-15T00:00:00Z",
    distanceKm: 1076320,
    distanceAu: 0.0072,
    distanceLunar: 2.8,
    speedKps: 12.4,
    speedKph: 44640,
    estimatedDiameterMinMeters: 42,
    estimatedDiameterMaxMeters: 95,
    estimatedDiameterDisplay: "Estimated 42-95 m",
    isPotentiallyHazardous: false,
    riskLevel: "safe",
    riskExplanation: "This object is passing at a large distance from Earth. It is useful for tracking and research, but it is not an impact concern.",
    sizeComparison: "roughly stadium-scale",
    distanceComparison: "About 2.8 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Close-approach tracking helps astronomers refine asteroid orbits and improve planetary-defense knowledge.",
    isFallback: true
  },
  {
    id: "2026 JL3",
    externalId: "2026 JL3",
    name: "2026 JL3",
    designation: "2026 JL3",
    closeApproachDate: "2026-05-18",
    closeApproachDateDisplay: "May 18, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-05-18T00:00:00Z",
    distanceKm: 1960440,
    distanceAu: 0.0131,
    distanceLunar: 5.1,
    speedKps: 8.9,
    speedKph: 32040,
    estimatedDiameterMinMeters: 18,
    estimatedDiameterMaxMeters: 41,
    estimatedDiameterDisplay: "Estimated 18-41 m",
    isPotentiallyHazardous: false,
    riskLevel: "safe",
    riskExplanation: "This object is passing at a large distance from Earth. It is useful for tracking and research, but it is not an impact concern.",
    sizeComparison: "roughly building-sized",
    distanceComparison: "About 5.1 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Objects like this help researchers understand the population of small bodies near Earth.",
    isFallback: true
  },
  {
    id: "2021 RP8",
    externalId: "2021 RP8",
    name: "2021 RP8",
    designation: "2021 RP8",
    closeApproachDate: "2026-05-23",
    closeApproachDateDisplay: "May 23, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-05-23T00:00:00Z",
    distanceKm: 3728680,
    distanceAu: 0.0249,
    distanceLunar: 9.7,
    speedKps: 21.1,
    speedKph: 75960,
    estimatedDiameterMinMeters: 110,
    estimatedDiameterMaxMeters: 250,
    estimatedDiameterDisplay: "Estimated 110-250 m",
    isPotentiallyHazardous: true,
    riskLevel: "watch",
    riskExplanation: "This object is officially classified for monitoring based on size and orbit, but that does not mean it will impact Earth.",
    sizeComparison: "very large asteroid-scale object",
    distanceComparison: "About 9.7 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Close-approach tracking helps astronomers refine asteroid orbits and improve planetary-defense knowledge.",
    isFallback: true
  },
  {
    id: "2019 VX4",
    externalId: "2019 VX4",
    name: "2019 VX4",
    designation: "2019 VX4",
    closeApproachDate: "2026-05-29",
    closeApproachDateDisplay: "May 29, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-05-29T00:00:00Z",
    distanceKm: 4766560,
    distanceAu: 0.0319,
    distanceLunar: 12.4,
    speedKps: 17.6,
    speedKph: 63360,
    estimatedDiameterMinMeters: 65,
    estimatedDiameterMaxMeters: 145,
    estimatedDiameterDisplay: "Estimated 65-145 m",
    isPotentiallyHazardous: false,
    riskLevel: "safe",
    riskExplanation: "This object is passing at a large distance from Earth. It is useful for tracking and research, but it is not an impact concern.",
    sizeComparison: "roughly stadium-scale",
    distanceComparison: "About 12.4 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Objects like this help researchers understand the population of small bodies near Earth.",
    isFallback: true
  },
  {
    id: "2026 KM4",
    externalId: "2026 KM4",
    name: "2026 KM4",
    designation: "2026 KM4",
    closeApproachDate: "2026-06-02",
    closeApproachDateDisplay: "June 2, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-06-02T00:00:00Z",
    distanceKm: 730360,
    distanceAu: 0.0049,
    distanceLunar: 1.9,
    speedKps: 6.3,
    speedKph: 22680,
    estimatedDiameterMinMeters: 9,
    estimatedDiameterMaxMeters: 21,
    estimatedDiameterDisplay: "Estimated 9-21 m",
    isPotentiallyHazardous: false,
    riskLevel: "notable",
    riskExplanation: "This is a relatively close astronomical pass, so it is interesting for observation and tracking, but current data does not indicate an impact.",
    sizeComparison: "roughly building-sized",
    distanceComparison: "About 1.9 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Close approaches like this help refine orbital models for small near-Earth objects.",
    isFallback: true
  },
  {
    id: "2014 QJ33",
    externalId: "2014 QJ33",
    name: "2014 QJ33",
    designation: "2014 QJ33",
    closeApproachDate: "2026-06-06",
    closeApproachDateDisplay: "June 6, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-06-06T00:00:00Z",
    distanceKm: 6457920,
    distanceAu: 0.0432,
    distanceLunar: 16.8,
    speedKps: 19.2,
    speedKph: 69120,
    estimatedDiameterMinMeters: 150,
    estimatedDiameterMaxMeters: 340,
    estimatedDiameterDisplay: "Estimated 150-340 m",
    isPotentiallyHazardous: true,
    riskLevel: "watch",
    riskExplanation: "This object is officially classified for monitoring based on size and orbit, but that does not mean it will impact Earth.",
    sizeComparison: "very large asteroid-scale object",
    distanceComparison: "About 16.8 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Monitoring larger near-Earth objects improves long-term orbit knowledge and survey completeness.",
    isFallback: true
  },
  {
    id: "2023 MT2",
    externalId: "2023 MT2",
    name: "2023 MT2",
    designation: "2023 MT2",
    closeApproachDate: "2026-06-10",
    closeApproachDateDisplay: "June 10, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-06-10T00:00:00Z",
    distanceKm: 2421720,
    distanceAu: 0.0162,
    distanceLunar: 6.3,
    speedKps: 10.8,
    speedKph: 38880,
    estimatedDiameterMinMeters: 26,
    estimatedDiameterMaxMeters: 59,
    estimatedDiameterDisplay: "Estimated 26-59 m",
    isPotentiallyHazardous: false,
    riskLevel: "safe",
    riskExplanation: "This object is passing at a large distance from Earth. It is useful for tracking and research, but it is not an impact concern.",
    sizeComparison: "roughly building-sized",
    distanceComparison: "About 6.3 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Objects like this help researchers understand the population of small bodies near Earth.",
    isFallback: true
  },
  {
    id: "2026 LE1",
    externalId: "2026 LE1",
    name: "2026 LE1",
    designation: "2026 LE1",
    closeApproachDate: "2026-06-12",
    closeApproachDateDisplay: "June 12, 2026, 00:00 UTC",
    closeApproachDateUtc: "2026-06-12T00:00:00Z",
    distanceKm: 1306960,
    distanceAu: 0.0087,
    distanceLunar: 3.4,
    speedKps: 7.1,
    speedKph: 25560,
    estimatedDiameterMinMeters: 7,
    estimatedDiameterMaxMeters: 16,
    estimatedDiameterDisplay: "Estimated 7-16 m",
    isPotentiallyHazardous: false,
    riskLevel: "notable",
    riskExplanation: "This is a relatively close astronomical pass, so it is interesting for observation and tracking, but current data does not indicate an impact.",
    sizeComparison: "roughly house-sized",
    distanceComparison: "About 3.4 lunar distances from Earth",
    source: "Mock",
    orbitingBody: "Earth",
    whyItMatters: "Close approaches like this help refine orbital models for small near-Earth objects.",
    isFallback: true
  }
];

export const mockCurrentSatelliteStatus: SatelliteStatus = {
  id: "mock-iss-current",
  noradId: 25544,
  name: "International Space Station",
  type: "ISS",
  latitude: 18.64,
  longitude: 73.21,
  timestamp: 1778664600,
  timestampDisplay: "May 13, 2026, 04:10 UTC",
  altitudeKm: 420,
  velocityKph: 27600,
  source: "Mock",
  isFallback: true
};

export const satellitePasses: SatellitePass[] = [
  {
    id: "pass-001",
    satelliteName: "International Space Station",
    noradId: 25544,
    locationName: "Ahmedabad, India",
    startTimeUtc: "2026-05-13T14:12:00.000Z",
    startTimeDisplay: "May 13, 2026, 14:12 UTC",
    maxTimeUtc: "2026-05-13T14:15:00.000Z",
    maxTimeDisplay: "May 13, 2026, 14:15 UTC",
    endTimeUtc: "2026-05-13T14:18:12.000Z",
    endTimeDisplay: "May 13, 2026, 14:18 UTC",
    durationSeconds: 372,
    durationDisplay: "6 min 12 sec",
    maxElevationDegrees: 72,
    startAzimuthDegrees: 248,
    startAzimuthCompass: "WSW",
    endAzimuthDegrees: 47,
    endAzimuthCompass: "NE",
    magnitude: -3.1,
    visibilityQuality: "sample",
    viewingAdvice: "This is sample pass data. Add an N2YO API key to enable live visible pass predictions.",
    source: "Mock",
    isFallback: true
  },
  {
    id: "pass-002",
    satelliteName: "International Space Station",
    noradId: 25544,
    locationName: "Ahmedabad, India",
    startTimeUtc: "2026-05-14T13:25:00.000Z",
    startTimeDisplay: "May 14, 2026, 13:25 UTC",
    maxTimeUtc: "2026-05-14T13:27:20.000Z",
    maxTimeDisplay: "May 14, 2026, 13:27 UTC",
    endTimeUtc: "2026-05-14T13:29:30.000Z",
    endTimeDisplay: "May 14, 2026, 13:29 UTC",
    durationSeconds: 270,
    durationDisplay: "4 min 30 sec",
    maxElevationDegrees: 41,
    startAzimuthDegrees: 226,
    startAzimuthCompass: "SW",
    endAzimuthDegrees: 68,
    endAzimuthCompass: "ENE",
    magnitude: -2.4,
    visibilityQuality: "sample",
    viewingAdvice: "This is sample pass data. Add an N2YO API key to enable live visible pass predictions.",
    source: "Mock",
    isFallback: true
  },
  {
    id: "pass-003",
    satelliteName: "International Space Station",
    noradId: 25544,
    locationName: "Ahmedabad, India",
    startTimeUtc: "2026-05-15T00:04:00.000Z",
    startTimeDisplay: "May 15, 2026, 00:04 UTC",
    maxTimeUtc: "2026-05-15T00:07:12.000Z",
    maxTimeDisplay: "May 15, 2026, 00:07 UTC",
    endTimeUtc: "2026-05-15T00:10:00.000Z",
    endTimeDisplay: "May 15, 2026, 00:10 UTC",
    durationSeconds: 360,
    durationDisplay: "6 min",
    maxElevationDegrees: 36,
    startAzimuthDegrees: 312,
    startAzimuthCompass: "NW",
    endAzimuthDegrees: 132,
    endAzimuthCompass: "SE",
    magnitude: -1.6,
    visibilityQuality: "sample",
    viewingAdvice: "This is sample pass data. Add an N2YO API key to enable live visible pass predictions.",
    source: "Mock",
    isFallback: true
  },
  {
    id: "pass-004",
    satelliteName: "International Space Station",
    noradId: 25544,
    locationName: "Ahmedabad, India",
    startTimeUtc: "2026-05-16T14:48:00.000Z",
    startTimeDisplay: "May 16, 2026, 14:48 UTC",
    maxTimeUtc: "2026-05-16T14:50:32.000Z",
    maxTimeDisplay: "May 16, 2026, 14:50 UTC",
    endTimeUtc: "2026-05-16T14:53:00.000Z",
    endTimeDisplay: "May 16, 2026, 14:53 UTC",
    durationSeconds: 300,
    durationDisplay: "5 min",
    maxElevationDegrees: 28,
    startAzimuthDegrees: 268,
    startAzimuthCompass: "W",
    endAzimuthDegrees: 91,
    endAzimuthCompass: "E",
    magnitude: -1.1,
    visibilityQuality: "sample",
    viewingAdvice: "This is sample pass data. Add an N2YO API key to enable live visible pass predictions.",
    source: "Mock",
    isFallback: true
  },
  {
    id: "pass-005",
    satelliteName: "International Space Station",
    noradId: 25544,
    locationName: "Ahmedabad, India",
    startTimeUtc: "2026-05-17T23:12:00.000Z",
    startTimeDisplay: "May 17, 2026, 23:12 UTC",
    maxTimeUtc: "2026-05-17T23:15:10.000Z",
    maxTimeDisplay: "May 17, 2026, 23:15 UTC",
    endTimeUtc: "2026-05-17T23:19:00.000Z",
    endTimeDisplay: "May 17, 2026, 23:19 UTC",
    durationSeconds: 420,
    durationDisplay: "7 min",
    maxElevationDegrees: 52,
    startAzimuthDegrees: 318,
    startAzimuthCompass: "NW",
    endAzimuthDegrees: 154,
    endAzimuthCompass: "SSE",
    magnitude: -2,
    visibilityQuality: "sample",
    viewingAdvice: "This is sample pass data. Add an N2YO API key to enable live visible pass predictions.",
    source: "Mock",
    isFallback: true
  }
];

export const learningPaths: LearningPath[] = [
  {
    id: "path-sky-watching",
    title: "Beginner Sky Watching",
    difficulty: "Beginner",
    time: "2 hours",
    progress: 18,
    visual: "horizon",
    description: "Learn constellations, sky direction, magnitude, and how to plan your first dark-sky session."
  },
  {
    id: "path-moon-basics",
    title: "Moon Basics",
    difficulty: "Beginner",
    time: "90 min",
    progress: 42,
    visual: "moon",
    description: "Understand phases, moonrise, lunar terrain, and why the Moon changes shape night by night."
  },
  {
    id: "path-asteroids-comets",
    title: "Asteroids and Comets",
    difficulty: "Starter",
    time: "3 hours",
    progress: 8,
    visual: "orbit",
    description: "Separate real risk from routine close approaches, and learn what orbital elements mean."
  },
  {
    id: "path-astronomy-briefs",
    title: "Reading Astronomy News",
    difficulty: "Beginner",
    time: "2.5 hours",
    progress: 27,
    visual: "mission",
    description: "Learn how to read space headlines, identify primary sources, and separate discovery from speculation."
  },
  {
    id: "path-exoplanets",
    title: "Exoplanets",
    difficulty: "Intermediate",
    time: "4 hours",
    progress: 12,
    visual: "transit",
    description: "Learn how transit, radial velocity, and spectroscopy reveal planets around other stars."
  },
  {
    id: "path-space-missions",
    title: "Space Missions",
    difficulty: "All levels",
    time: "3 hours",
    progress: 33,
    visual: "mission",
    description: "Follow launches, cruise phases, flybys, orbital insertion, and science operations."
  }
];

export const articles: Article[] = [
  {
    id: "article-001",
    slug: "meteor-shower-forecast",
    title: "How to read a meteor shower forecast without getting disappointed",
    category: "Sky Watching",
    tag: "Beginner",
    readTime: "7 min",
    description: "Zenithal hourly rate, moonlight, radiant height, and why patient observing matters.",
    featured: true
  },
  {
    id: "article-002",
    slug: "lunar-terminator-observing",
    title: "The terminator is the best place to start lunar observing",
    category: "Moon",
    tag: "Guide",
    readTime: "6 min",
    description: "A practical tour of shadows, crater relief, and changing surface detail."
  },
  {
    id: "article-003",
    slug: "close-approach-not-danger",
    title: "Close approach does not mean close danger",
    category: "Asteroids",
    tag: "Explainer",
    readTime: "8 min",
    description: "Lunar distances, uncertainty, Torino scale basics, and responsible reporting."
  },
  {
    id: "article-004",
    slug: "read-space-agency-update",
    title: "How to read a space agency update",
    category: "Missions",
    tag: "Field Notes",
    readTime: "5 min",
    description: "Status language, source links, mission timelines, and what a cautious update usually means."
  },
  {
    id: "article-005",
    slug: "launch-window-narrow",
    title: "What makes a launch window narrow",
    category: "Missions",
    tag: "Mission Ops",
    readTime: "9 min",
    description: "Orbital mechanics, target planes, weather rules, and range constraints."
  },
  {
    id: "article-006",
    slug: "cosmic-distance-ladder",
    title: "How astronomers estimate distance in deep space",
    category: "Cosmology",
    tag: "Foundations",
    readTime: "10 min",
    description: "Parallax, standard candles, redshift, and the cosmic distance ladder."
  },
  {
    id: "article-007",
    slug: "choose-first-telescope",
    title: "How to choose a first telescope without overspending",
    category: "Basics",
    tag: "Buying Guide",
    readTime: "8 min",
    description: "Aperture, mounts, eyepieces, portability, and why binoculars are often the better first tool."
  },
  {
    id: "article-008",
    slug: "why-planets-retrograde",
    title: "Why planets sometimes move backward in the sky",
    category: "Sky Watching",
    tag: "Explainer",
    readTime: "6 min",
    description: "Retrograde motion explained through Earth's faster inside track around the Sun."
  }
];

export const toolCards: ToolCard[] = [
  {
    title: "Moon Dashboard",
    href: "/moon",
    description: "Phase, illumination, viewing time, and a lunar cycle strip.",
    status: "Ready"
  },
  {
    title: "Asteroid Watch",
    href: "/asteroids",
    description: "Educational NEO tracking with safe-language risk explanations.",
    status: "Ready"
  },
  {
    title: "Astronomy Briefs",
    href: "/briefs",
    description: "Short, clear explanations of major astronomy and space updates.",
    status: "Ready"
  }
];
